FROM python:3.12-slim as dependencies

ENV APP_PATH /usr/src/app
ENV TIMEZONE 'America/Manaus'
WORKDIR $APP_PATH

RUN mkdir -p $APP_PATH \
  && apt-get update && apt-get install -y \
    apt-transport-https \
    unixodbc \
    unixodbc-dev \
    build-essential \
    ncurses-dev \
    gettext \
    libpq-dev \
    python3-dev \
    libsasl2-dev \
    libldap2-dev \
    libssl-dev \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && echo $TIMEZONE > /etc/timezone \
  && rm /etc/localtime \
  && ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

FROM dependencies as application

COPY requirements.txt $APP_PATH

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt