# Generated by Django 5.0.6 on 2024-05-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', error_messages={'unique': 'This city name already exists.'}, max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Marital status',
                'db_table': 'marital_status',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('commission_percentage', models.DecimalField(db_column='commission_percentage', decimal_places=2, max_digits=5, verbose_name='Commission percentage')),
                ('gain_percentage', models.DecimalField(db_column='gain_percentage', decimal_places=2, max_digits=5, verbose_name='Gain percentage')),
            ],
            options={
                'verbose_name': 'Product group',
                'db_table': 'product_group',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', error_messages={'unique': 'This state name already exists.'}, max_length=64, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(db_column='abbreviation', error_messages={'unique': 'This abbreviation already exists.'}, max_length=2, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'State',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('legal_document', models.CharField(db_column='legal_document', max_length=20, unique=True, verbose_name='Legal document')),
            ],
            options={
                'verbose_name': 'Supplier',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', error_messages={'unique': 'This zone name already exists.'}, max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Zone',
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', error_messages={'unique': 'This district name already exists.'}, max_length=64, unique=True, verbose_name='Name')),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.DO_NOTHING, to='core.city')),
                ('zone', models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.DO_NOTHING, to='core.zone')),
            ],
            options={
                'verbose_name': 'District',
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, to='core.district')),
            ],
            options={
                'verbose_name': 'Branch',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('salary', models.DecimalField(db_column='salary', decimal_places=2, max_digits=16, verbose_name='Salary')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='gender', max_length=1)),
                ('admission_date', models.DateField(db_column='admission_date', verbose_name='Admission date')),
                ('birth_date', models.DateField(db_column='birth_date', verbose_name='Birth date')),
                ('department', models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.DO_NOTHING, to='core.department', verbose_name='Department')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, to='core.district', verbose_name='District')),
                ('marital_status', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.DO_NOTHING, to='core.maritalstatus', verbose_name='Marital status')),
            ],
            options={
                'verbose_name': 'Employee',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('income', models.DecimalField(db_column='income', decimal_places=2, max_digits=16, verbose_name='Income')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='gender', max_length=1, verbose_name='Gender')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, to='core.district')),
                ('marital_status', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.DO_NOTHING, to='core.maritalstatus')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='name', max_length=64, verbose_name='Name')),
                ('cost_price', models.DecimalField(db_column='cost_price', decimal_places=2, max_digits=16, verbose_name='Cost price')),
                ('sale_price', models.DecimalField(db_column='sale_price', decimal_places=2, max_digits=16, verbose_name='Sale price')),
                ('product_group', models.ForeignKey(db_column='id_product_group', on_delete=django.db.models.deletion.DO_NOTHING, to='core.productgroup', verbose_name='Product group')),
                ('supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.DO_NOTHING, to='core.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': ('Product',),
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('date', models.DateField(auto_now_add=True, db_column='date', verbose_name='Date')),
                ('branch', models.ForeignKey(db_column='id_branch', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch', verbose_name='Branch')),
                ('customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='core.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Sale',
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=3, max_digits=16, verbose_name='Quantity')),
                ('product_price', models.DecimalField(db_column='product_price', decimal_places=2, default=0, max_digits=16, verbose_name='Product price')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='Product')),
                ('sale', models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.DO_NOTHING, to='core.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale item',
                'db_table': 'sale_item',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.DO_NOTHING, to='core.state'),
        ),
    ]
