# Generated by Django 5.0.6 on 2024-05-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='core.department', verbose_name='Department'),
        ),
    ]
